# Site settings
title: blank
first_name: Shadman
middle_name: 
last_name: Ahmmed
email: shadmanahmmed@gmail.com
description: Flutter Mobile App Developer passionate about building cross-platform mobile applications.

lang: en
icon: 🚀

url: https://coderboxer.github.io
baseurl: 

# Social integration
github_username: CoderBoxer
linkedin_username: shadman-ahmmed

# Layout
navbar_fixed: true
footer_fixed: true
max_width: 800px

# Theme
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# Display settings  
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  enabled: true
  scrollable: true
  limit: 5

latest_posts:
  enabled: true
  scrollable: true
  limit: 3

# Jekyll settings
markdown: kramdown
highlighter: rouge
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-sitemap
  - jemoji

# Scholar settings
scholar:
  last_name: [Ahmmed]
  first_name: [Shadman]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  query: "@*"
  group_by: year
  group_order: descending
